sonar.projectKey=lauringlarner_Client_SOPRA
sonar.organization=lauringlarner Cloud>

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=app